### ISSUE TITLE
User name 중복 체크

### ISSUE THREAD

**Issue by sanggggg** [wafflestudio/draft-server#50]
/api/v1/user/check-valid-username/ 과 같은 형태로

- 명세
    - request : `{"username":"username"}`
    - response : 중복이름이면 4XX, 사용가능한 이름이면 2XX 를 보내는 간단한 api

- 사용처
    - signup 시에 이름, 지역, 시간대 다 입력하고 중복이라고 뜨면 빡치니까, 그냥 이름만 써도 일단 확인할 수 있게하는 뷰가 필요
<img width="389" alt="스크린샷 2020-07-25 오후 12 18 16" src="https://user-images.githubusercontent.com/37951125/88447686-ef059180-ce70-11ea-9b9d-8454a89e7acb.png">
이거처럼!

**Comment by davin111** [comment]
중복일 때 409 CONFLICT 어때요? 이런 경우 많이들 쓰는 거 같던데 @sanggggg @zlzlqlzl

**Comment by davin111** [comment]
ㅋㅋㅋ 근데 API는 /signup/ 하나로 하고, 클라에서 다 입력하고서 fail 나도 입력 값들을 잃어버리지 않게 처리해도 되지 않을까요? @sanggggg

**Comment by sanggggg** [comment]
ui 에서 원하는 부분만 입력한 후에도 해당 부분의 validation을 체크하고 싶어서 따로 api-endpoint 를 마련하고 싶어요
