### ISSUE TITLE
region fetch 성능 개선

### ISSUE THREAD

**Issue by Hank-Choi** [wafflestudio/draft-server#80]
region fetch 시 lazy fetch가 동작하지 않아 매우 성능이 느림.
개선 필요

**Comment by davin111** [comment]
@Hank-Choi 요건 #79 와 관련 있는 pagination으로 해소할 수 있는 부분이기도 한듯.(근데 그냥 pagination 자체는 별도 이슈로 해도 될 거 같기도 하고. 어케 생각?) 근데 lazy fetch 문제도 있었구나. 이 부분은 어케 알았어?

**Comment by davin111** [comment]
=> 아마 #81 을 보아하니 pagination은 별도 이슈로 생각한 거 같아서, https://trello.com/c/v4RdZNGN 이거 따로 만들었어.

**Comment by Hank-Choi** [comment]
지금 바로 pagination이 필요한 부분이 어떤 endpoint지??

**Comment by davin111** [comment]
@Hank-Choi 이 이슈 이제 close 해도 되는 거지?

**Comment by Hank-Choi** [comment]
얍
