### ISSUE TITLE
javax validation annotation을 통한 Validation 문제

### ISSUE THREAD

**Issue by Hank-Choi** [wafflestudio/draft-server#93]
#91  #78 에서 언급된 것 처럼 @valid 가 제대로 동작하지 않는 이슈

**Comment by davin111** [comment]
머지? 이거 왜 close 안 되었지, resolve command도 인식되었는데

**Comment by davin111** [comment]
아 https://github.com/wafflestudio/draft-server/pull/95#issuecomment-770916917 때문이네
